#!/bin/bash

echo 'symbol,slow_macd_period,fast_macd_period,macd_signal_period,atr_period,atr_dist,sma_period,direction_period,profit,Sharpe_ratio,max_drawdown,max_drawdown_duration,profit_vs_BuyHold' >final_results.csv

declare -a symbols=("ALGOUSDT" "ETHUSDT" "LTCUSDT" "XMRUSDT")

for symbol in "${symbols[@]}"
do
	python3 -u backtest_MACD.py $symbol 24 52 18 14 3 30 10
done
